### ISSUE TITLE
RuntimeError: value cannot be converted to type float without overflow

### ISSUE THREAD

**Issue by dgks0n** [warmspringwinds/pytorch-segmentation-detection#21]
Hi, I try to train model using python 3, but I got below issue:

```
/home/v2m/anaconda3/envs/my_env3/lib/python3.7/site-packages/torch/nn/_reduction.py:46: UserWarning: size│
_average and reduce args will be deprecated, please use reduction='sum' instead.                         │
  warnings.warn(warning.format(ret))                                                                     │
/home/v2m/anaconda3/envs/my_env3/lib/python3.7/site-packages/torch/nn/functional.py:2622: UserWarning: nn│
.functional.upsample_bilinear is deprecated. Use nn.functional.interpolate instead.                      │
  warnings.warn("nn.functional.upsample_bilinear is deprecated. Use nn.functional.interpolate instead.") │
0.4247354666311015                                                                                       │
0.5617590819998219                                                                                       │
0.5815541637890524                                                                                       │
0.6344758887881029                                                                                       │
Traceback (most recent call last):                                                                       │
  File "pytorch_segmentation_detection/recipes/pascal_voc/segmentation/psp_resnet_50_8s_train.py", line 3│
76, in <module>                                                                                          │
    optimizer.step()                                                                                     │
  File "/home/v2m/anaconda3/envs/my_env3/lib/python3.7/site-packages/torch/optim/adam.py", line 107, in s│
tep                                                                                                      │
    p.data.addcdiv_(-step_size, exp_avg, denom)                                                          │
RuntimeError: value cannot be converted to type float without overflow: (3.52033e-08,-1.14383e-08)
```

Can someone give me suggestion?

**Comment by dgks0n** [comment]
Hello Daniil,

I saw in the `psp_resnet_50_8s_synch_bn_train.py` script file, the settings for learning rate is `0.0001` and number of step is 13000.0 then I faced above issue.

Do you think it's small?

**Comment by J-Wu97** [comment]
> Hello Daniil,
> 
> I saw in the `psp_resnet_50_8s_synch_bn_train.py` script file, the settings for learning rate is `0.0001` and number of step is 13000.0 then I faced above issue.
> 
> Do you think it's small?

Hi 
I get the same error as you. Have you addressed this problem?
Thanks for your reply
